/*CREACION USUARIO DUEÑO DE TABLAS*/
CREATE USER "USUARIODUENO" IDENTIFIED BY "Proyectoplsqldueno"  
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER "USUARIODUENO" QUOTA UNLIMITED ON "DATA";


/*CREACION USUARIO DESARROLLADOR 1*/
-- USER SQL
CREATE USER "DESARROLLADOR1" IDENTIFIED BY "Proyectoplsqldev1"  
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER "DESARROLLADOR1" QUOTA UNLIMITED ON "DATA";



/*CREACION USUARIO DESARROLLADOR 2*/




