/*CREACION USUARIO DUEÑO DE TABLAS*/
CREATE USER "USUARIODUENO" IDENTIFIED BY "Proyectoplsqldueno1"  
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER "USUARIODUENO" QUOTA UNLIMITED ON "DATA";


/*CREACION USUARIO DESARROLLADOR 1*/
CREATE USER "DESARROLLADOR1" IDENTIFIED BY "Proyectoplsqldev1"  
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER "DESARROLLADOR1" QUOTA UNLIMITED ON "DATA";



/*CREACION USUARIO DESARROLLADOR 2*/
CREATE USER "DESARROLLADOR2" IDENTIFIED BY "Proyectoplsqldev2"  
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER "DESARROLLADOR2" QUOTA UNLIMITED ON "DATA";







