/*
Requerimiento 2.2.1 RESUMEN DEL TOTAL DE POSTULANTES A LA BECA POR REGION

Ejecutar como Usuario Dueño de las Tablas
*/

SELECT
    COUNT(
        CASE
            WHEN R.NOMBRE_REGION = 'TARAPACÁ' THEN P.NUMRUN
        END
    ) AS TARAPACÁ,
    
    COUNT(
        CASE
            WHEN R.NOMBRE_REGION = 'ATACAMA' THEN P.NUMRUN
        END
    ) AS ATACAMA,
    
    COUNT(
        CASE
            WHEN R.NOMBRE_REGION = 'COQUIMBO' THEN P.NUMRUN
        END
    ) AS COQUIMBO,
    
    COUNT(
        CASE
            WHEN R.NOMBRE_REGION = 'VALPARAÍSO' THEN P.NUMRUN
        END
    ) AS VALPARAÍSO,
    
    COUNT(
        CASE
            WHEN R.NOMBRE_REGION = 'DEL LIBERTADOR GRAL. BERNARDO O’HIGGINS' THEN P.NUMRUN
        END
    ) AS "LIB. GRAL. BERNARDO O’HIGGINS",
    
    COUNT(
        CASE
            WHEN R.NOMBRE_REGION = 'DE LA ARAUCANÍA' THEN P.NUMRUN
        END
    ) AS "ARAUCANÍA",
    
    COUNT(
        CASE
            WHEN R.NOMBRE_REGION = 'DE MAGALLANES Y DE LA ANTÁRTICA CHILENA' THEN P.NUMRUN
        END
    ) AS "MAGALLANES Y DE LA ANTÁRTICA CHILENA",
    
    COUNT(
        CASE
            WHEN R.NOMBRE_REGION = 'METROPOLITANA DE SANTIAGO' THEN P.NUMRUN
        END
    ) AS "METROPOLITANA DE SANTIAGO",
    
    COUNT(
        CASE
            WHEN R.NOMBRE_REGION = 'ARICA Y PARINACOTA' THEN P.NUMRUN
        END
    ) AS "ARICA Y PARINACOTA"
    
FROM POSTULANTE P
JOIN COMUNA C ON P.ID_COMUNA = C.ID_COMUNA AND P.ID_REGION = C.ID_REGION
JOIN REGION R ON R.ID_REGION = C.ID_REGION;






