/*
Requerimiento 2.2.2 DETALLE DE POSTULANTES A LA BECA

Ejecutar como Usuario Desarrollador 1
*/

--CREACION DE SECUENCIA COMO DUEÑO DE LAS TABLAS
CREATE SEQUENCE SEQ_RUN
INCREMENT BY 3
START WITH 10
MAXVALUE 1000
MINVALUE 10;

CREATE SEQUENCE SEQ_DVRUN;

--CONSULTA COMO DESARROLLADOR 2
SELECT
    P.NUMRUN||SUBSTR(P.PNOMBRE,1,2)||'-'||P.DVRUN AS "RUN POSTULANTE",
    P.PNOMBRE||' '||P.SNOMBRE||' '||P.APPATERNO||' '||P.APMATERNO AS "NOMBRE POSTULANTE",
    TO_CHAR(F.FECHA_POSTULACION,'DD/MM/YYYY') AS "FECHA POSTULACION",
    EC.NOMBRE_ESTADO_CIVIL AS "EST. CIVIL",
    P.DIRECCION,
    S.NOMBRE_SUBESP AS "SUBESPECIALIDAD A LA QUE POSTULA",
    I.NOMBRE_INSTITUCION AS "INSTITUCION ACADEMICA",
    CI.NOMBRE_CIUDAD_INST AS CIUDAD,
    PI.NOMBRE_PAIS AS PAIS
FROM POSTULANTE P
JOIN FORMULARIO_POSTULACION F
ON P.NUMRUN = F.NUMRUN
JOIN ESTADO_CIVIL EC
ON P.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
JOIN SUBESPECIALIDAD S
ON F.ID_SUBESP = S.ID_SUBESP
JOIN INSTITUCION_ACADEMICA I
ON F.ID_INSTITUCION = I.ID_INSTITUCION
JOIN CIUDAD_INST CI
ON I.ID_CIUDAD_INST = CI.ID_CIUDAD_INST AND I.ID_PAIS_INST = CI.ID_PAIS_INST
JOIN PAIS_INST PI
ON CI.ID_PAIS_INST = PI.ID_PAIS_INST
;

/*
POSTULANTE
FORMULARIO_POSTULACION
ESTADO_CIVIL
SUBESPECIALIDAD
INSTITUCION_ACADEMICA
CIUDAD_INST
PAIS_INST
*/
