/*
Requerimiento 2.2.3 PUNTAJES OBTENIDOS POR CADA POSTULANTE A LA BECA

Ejecutar como Usuario Desarrollador 2
*/
CREATE VIEW V_PUNTAJES_POSTULANTE AS
SELECT
        NUMRUN AS "RUN POSTULANTE",
        NOMBRE AS "NOMBRE POSTULANTE",
        EDAD,
        PTJE_EDAD AS "PTJE. EDAD",
        EST_CIVIL AS "EST. CIVIL",
        PTJE_EST_CIVIL AS "PTJE. EST. CIVIL",
        PUEBLO_IND_ORIG AS "PUEBLO IND. ORIG",
        PTJE_PUEBLO AS "PTJE. PUEBLO IND. ORIG",
        PTJE_ZONA AS "PTJE. ZONA EXTREMA",
        PTJE_ACAD AS "PTJE. ANTEC. ACAD",
        PTJE_EXP AS "PTJE. TRAYECT./EXP. LABORAL",
        PTJE_DOCENCIA AS "PTJE. DOCENCIA/INVEST",
        PTJE_OBJETIVO AS "PTJE. OBJETIVO ESTUDIO",
        PTE_INTERESES AS "PTJE. INTERESES",
        PTJE_RETRIBUCION AS "PTJE. RETRIB",
        PTJE_RANKING AS " PTJE. RANKING INT. EDUC. EXTRANJERA",
        PTJE_EDAD+PTJE_EST_CIVIL+PTJE_PUEBLO+PTJE_ZONA+PTJE_ACAD+PTJE_EXP+PTJE_DOCENCIA+PTJE_OBJETIVO+PTE_INTERESES+PTJE_RETRIBUCION+PTJE_RANKING AS "PTJE. TOTAL"
FROM
(SELECT
        TO_CHAR(P.NUMRUN,'09G999G999')||'-'||P.DVRUN AS NUMRUN,
        P.PNOMBRE||' '||P.SNOMBRE||' '||P.APPATERNO||' '||P.APMATERNO AS NOMBRE,
        TRUNC(MONTHS_BETWEEN(SYSDATE,P.FECHA_NAC)/12) AS EDAD,
        
        CASE
            WHEN TRUNC(MONTHS_BETWEEN(SYSDATE,P.FECHA_NAC)/12)<30 THEN 5
            WHEN TRUNC(MONTHS_BETWEEN(SYSDATE,P.FECHA_NAC)/12) BETWEEN 30 AND 40 THEN 3
            WHEN TRUNC(MONTHS_BETWEEN(SYSDATE,P.FECHA_NAC)/12)>40 THEN 1
        END AS PTJE_EDAD,
        
        NOMBRE_ESTADO_CIVIL AS EST_CIVIL,
        
        CASE
            WHEN NOMBRE_ESTADO_CIVIL = 'Casado' THEN 5
            WHEN NOMBRE_ESTADO_CIVIL = 'Conviviente Civil' THEN 4
            WHEN NOMBRE_ESTADO_CIVIL = 'Soltero' THEN 3
            WHEN NOMBRE_ESTADO_CIVIL = 'Divorciado' THEN 2
            WHEN NOMBRE_ESTADO_CIVIL = 'Viudo' THEN 1
        END AS PTJE_EST_CIVIL,
        
        CASE
            WHEN PO.ID_PUEBLO IS NOT NULL THEN 'Si'
            ELSE 'No'
        END AS PUEBLO_IND_ORIG,
        
        CASE
            WHEN PO.ID_PUEBLO IS NOT NULL THEN 5
            ELSE 0
        END AS PTJE_PUEBLO,
        
        CASE
            WHEN R.NOMBRE_REGION = 'ARICA Y PARINACOTA' THEN 5
            WHEN R.NOMBRE_REGION = 'TARAPACÁ' THEN 4
            WHEN R.NOMBRE_REGION = 'AYSÉN DEL GRAL.CARLOS IBAÑEZ DEL CAMPO' THEN 4
            WHEN R.NOMBRE_REGION = 'DE MAGALLANES Y DE LA ANTÁRTICA CHILENA' THEN 5
            ELSE 0
        END AS PTJE_ZONA,
        
        RN.PTJE_NOTAS AS PTJE_ACAD,
        
        CASE
            WHEN TRUNC(MONTHS_BETWEEN(EL.FECHA_TERMINO,EL.FECHA_INICIO)/12) > 5 THEN 5
            WHEN TRUNC(MONTHS_BETWEEN(EL.FECHA_TERMINO,EL.FECHA_INICIO)/12) = 5 THEN 4
            WHEN TRUNC(MONTHS_BETWEEN(EL.FECHA_TERMINO,EL.FECHA_INICIO)/12) = 4 THEN 3
            WHEN TRUNC(MONTHS_BETWEEN(EL.FECHA_TERMINO,EL.FECHA_INICIO)/12) = 3 THEN 2
            WHEN TRUNC(MONTHS_BETWEEN(EL.FECHA_TERMINO,EL.FECHA_INICIO)/12) = 2 THEN 1
            ELSE 0
        END AS PTJE_EXP,
        
        CASE
            WHEN D.DESC_DOCENCIA_INV = 'ALTA' THEN 5
            WHEN D.DESC_DOCENCIA_INV = 'MEDIA' THEN 3
            WHEN D.DESC_DOCENCIA_INV = 'BAJA' THEN 2
        END AS PTJE_DOCENCIA,
        
        CASE
            WHEN OE.DESC_OBJETIVO = 'EXCELENTE' THEN 5
            WHEN OE.DESC_OBJETIVO = 'MUY BUENO' THEN 4
            WHEN OE.DESC_OBJETIVO = 'BUENO' THEN 3
            WHEN OE.DESC_OBJETIVO = 'REGULAR' THEN 1
        END AS PTJE_OBJETIVO,
        
        CASE
            WHEN DI.DESC_INTERESES = 'EXCELENTE' THEN 5
            WHEN DI.DESC_INTERESES = 'MUY BUENO' THEN 4
            WHEN DI.DESC_INTERESES = 'BUENO' THEN 3
            WHEN DI.DESC_INTERESES = 'REGULAR' THEN 1
        END AS PTE_INTERESES,
        
        CASE
            WHEN RE.DESC_RETRIBUCION = 'EXCELENTE' THEN 5
            WHEN RE.DESC_RETRIBUCION = 'MUY BUENO' THEN 4
            WHEN RE.DESC_RETRIBUCION = 'BUENO' THEN 3
            WHEN RE.DESC_RETRIBUCION = 'REGULAR' THEN 1
        END AS PTJE_RETRIBUCION,
        
        RPR.PTJE_RANKING AS PTJE_RANKING
             
FROM USUARIODUENO.POSTULANTE P
                JOIN USUARIODUENO.ESTADO_CIVIL EC ON P.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
                LEFT JOIN USUARIODUENO.PUEBLO_ORIGINARIO PO ON P.ID_PUEBLO = PO.ID_PUEBLO
                JOIN USUARIODUENO.COMUNA CO ON P.ID_COMUNA = CO.ID_COMUNA AND P.ID_REGION = CO.ID_REGION
                JOIN USUARIODUENO.REGION R ON CO.ID_REGION = R.ID_REGION
                JOIN USUARIODUENO.RANGO_NOTAS RN ON P.NOTA_PREGRADO BETWEEN RN.NOTA_MIN AND RN.NOTA_MAX
                JOIN USUARIODUENO.EXPERIENCIA_LABORAL EL ON P.NUMRUN = EL.NUMRUN
                JOIN USUARIODUENO.FORMULARIO_POSTULACION F ON P.NUMRUN = F.NUMRUN
                JOIN USUARIODUENO.DOCENCIA_INVEST D ON F.ID_DOCENCIA_INV = D.ID_DOCENCIA_INV
                JOIN USUARIODUENO.OBJETIVO_ESTUDIO OE ON F.ID_OBJETIVO = OE.ID_OBJETIVO
                JOIN USUARIODUENO.DECLARACION_INTERESES DI ON F.ID_INTERESES = DI.ID_INTERESES
                JOIN USUARIODUENO.RETRIBUCION RE ON F.ID_RETRIBUCION = RE.ID_RETRIBUCION
                JOIN USUARIODUENO.INSTITUCION_ACADEMICA INST ON F.ID_INSTITUCION = INST.ID_INSTITUCION
                JOIN USUARIODUENO.RANGO_PTJE_RANKING RPR ON INST.RANKING_INST BETWEEN RPR.RANKING_MIN AND RPR.RANKING_MAX
ORDER BY P.APPATERNO DESC)
ORDER BY "PTJE. TOTAL"
;
/
SELECT * FROM V_PUNTAJES_POSTULANTE;